<?php

namespace NeigeEtSoleilBundle\Repository;

/**
 * AppartementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartementsRepository extends \Doctrine\ORM\EntityRepository
{
}
