<?php

namespace NeigeEtSoleilBundle\Repository;

/**
 * contratLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contratLRepository extends \Doctrine\ORM\EntityRepository
{
}
