<?php

namespace NeigeEtSoleilBundle\Repository;

/**
 * contratPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contratPRepository extends \Doctrine\ORM\EntityRepository
{
}
