<?php

namespace NeigeEtSoleilBundle\Repository;

/**
 * RepresentantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentantsRepository extends \Doctrine\ORM\EntityRepository
{
}
