<?php

namespace NeigeEtSoleilBundle\Repository;

/**
 * SaisonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonsRepository extends \Doctrine\ORM\EntityRepository
{
}
