<?php

namespace NeigeEtSoleilBundle\Repository;

/**
 * TypeAppartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAppartementRepository extends \Doctrine\ORM\EntityRepository
{
}
